name: Rub Unit Tests

on: [push]

jobs:
   run-unit-tests:
      name: Run Unit Tests
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v5
         - uses: actions/setup-node@v5
           with:
             node-version: 24
             cache: 'npm'
         - run: npm ci
         - run: npm run test 

